id: TestProofpointFeed
version: -1
contentitemfields:
  propagationLabels:
  - all
name: TestProofpointFeed
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 28f9f08f-5697-457c-85aa-a0db8887c3e9
    type: start
    task:
      id: 32374b87-da6e-47bb-876b-74e0b54edf8d
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 690,
          "y": 40
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: 481e051d-01a2-4bf8-8057-ef25fb4f0b91
    type: regular
    task:
      id: 481e051d-01a2-4bf8-8057-ef25fb4f0b91
      version: -1
      name: all indicators
      description: Gets indicators from the feed.
      script: ProofpointFeed|||proofpoint-get-indicators
      type: regular
      iscommand: true
      brand: ProofpointFeed
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      indicator_type:
        simple: all
      limit: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: 95b4e538-fb81-45eb-801c-7c058c0d13b7
    type: regular
    task:
      id: 95b4e538-fb81-45eb-801c-7c058c0d13b7
      version: -1
      name: ips
      description: Gets indicators from the feed.
      script: ProofpointFeed|||proofpoint-get-indicators
      type: regular
      iscommand: true
      brand: ProofpointFeed
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      indicator_type:
        simple: ip
      limit: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: 5ac72305-e0d9-470e-8121-7fd668c10937
    type: regular
    task:
      id: 5ac72305-e0d9-470e-8121-7fd668c10937
      version: -1
      name: domains
      description: Gets indicators from the feed.
      script: ProofpointFeed|||proofpoint-get-indicators
      type: regular
      iscommand: true
      brand: ProofpointFeed
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      indicator_type:
        simple: domain
      limit: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: 9e68bd6f-59dd-4ea0-8a78-d599cb1f3c08
    type: title
    task:
      id: 9e68bd6f-59dd-4ea0-8a78-d599cb1f3c08
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 700,
          "y": 550
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: a1e21b2f-4e94-4e7d-8706-94dccfca90bd
    type: regular
    task:
      id: a1e21b2f-4e94-4e7d-8706-94dccfca90bd
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
      - "2"
      - "3"
      - "6"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 690,
          "y": 185
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "6":
    id: "6"
    taskid: b330b7c4-43f6-4991-8773-b9f2340476e5
    type: regular
    task:
      id: b330b7c4-43f6-4991-8773-b9f2340476e5
      version: -1
      name: domainGlobs
      description: Gets indicators from the feed.
      script: ProofpointFeed|||proofpoint-get-indicators
      type: regular
      iscommand: true
      brand: ProofpointFeed
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      indicator_type:
        simple: domainGlob
      limit: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1380,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 575,
        "width": 1710,
        "x": 50,
        "y": 40
      }
    }
  }
inputs: []
outputs: []
